services:
  backend:
    image: infinitepumpkin/home-server:latest
    ports:
      - 3333:3333
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db-password

  db:
    image: mysql:latest
    ports:
      - 5123:3306
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - home-server-data:/var/lib/mysql
    secrets:
      - db_password

  dashboard:
    image: metabase/metabase:latest
    ports:
      - 3334:3000
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - home-server-metabase-data:/metabase-data

secrets:
  db_password:
    file: db-password.txt

volumes:
  home-server-data:
    external: true
  home-server-metabase-data:
    external: true
