services:
  backend:
    image: home-server:latest
    ports:
      - 3333:3333
    networks:
      - home-server-network
    environment:
      - DB_HOST=unknown
      - DB_USER=root
      - DB_PASSWORD=/run/secrets/db-password
    secrets:
      - db-password

  db:
    image: mysql:latest
    ports:
      - 3335:3306
    networks:
      - home-server-network
    environment:
      - MYSQL_ROOT_PASSWORD=/run/secrets/db-password
    volumes:
      - home-server-data:/var/lib/mysql
    secrets:
      - db-password

  dashboard:
    image: metabase/metabase:latest
    ports:
      - 3334:3000
    networks:
      - home-server-network
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    volumes:
      - home-server-metabase-data:/metabase-data

secrets:
  db-password:
    file: ./db-password.txt